web:
  image: abryrath/craft
  ports: 
    - "8080:80"
  links:
    - db
    - selenium
  volumes:
    - ./app:/var/www
    - ../tests:/var/www/tests
    - ../:/var/www/plugin
    - ./app/web:/var/www/html
    # - ./scripts:/root/scripts

db:
  image: mariadb
  restart: always
  volumes:
    - ./mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: test
    MYSQL_PASSWORD: test
    MYSQL_DATABASE: database
  ports:
    - "8889:3306"

selenium:
  image: selenium/standalone-chrome
  volumes:
    - /dev/shm:/dev/shm
  ports:
    - "4444:4444"
  